//CHECKING DATA
SELECT 'Data-FD_GROUP_INGEST' as data_confirmed, COUNT(*) AS ROWS_FOUND, '25' AS 
ROWS_EXPECTED
FROM "USDA_NUTRIENT_STDREF"."PUBLIC"."FD_GROUP_INGEST"
WHERE FDGRP_DESC like '%~%'
UNION
SELECT 'Data-WEIGHT' as data_confirmed, COUNT(*) AS FOUND, '14449' AS EXPECTED
FROM "USDA_NUTRIENT_STDREF"."PUBLIC"."WEIGHT"
WHERE NDB_NO not like '%~%' 
UNION
SELECT 'Data-WEIGHT_INGEST' as data_confirmed, COUNT(*) AS FOUND, '14449' AS EXPECTED
FROM "USDA_NUTRIENT_STDREF"."PUBLIC"."WEIGHT_INGEST"
WHERE NDB_NO like '%~%'
UNION
SELECT 'Data-LANGDESC' as data_confirmed, COUNT(*) AS FOUND, '773' AS EXPECTED
FROM "USDA_NUTRIENT_STDREF"."PUBLIC"."LANGDESC"
WHERE FACTOR_CODE NOT like '%~%'
UNION
SELECT 'Data-BOOK' as data_confirmed, COUNT(*) AS FOUND, '5' AS EXPECTED
FROM "LIBRARY_CARD_CATALOG"."PUBLIC"."BOOK"
UNION
SELECT 'Data-AUTHOR' as data_confirmed, COUNT(*) AS FOUND, '6' AS EXPECTED
FROM "LIBRARY_CARD_CATALOG"."PUBLIC"."AUTHOR"
UNION
SELECT 'Data-BOOK_TO_AUTHOR' as data_confirmed, COUNT(*) AS FOUND, '6' AS EXPECTED
FROM "LIBRARY_CARD_CATALOG"."PUBLIC"."BOOK_TO_AUTHOR"
UNION
SELECT 'Data-AUTHOR_INGEST_XML' as data_confirmed, COUNT(*) AS FOUND, '12' AS EXPECTED
FROM "LIBRARY_CARD_CATALOG"."PUBLIC"."AUTHOR_INGEST_XML"
UNION
SELECT 'Data-AUTHOR_INGEST_JSON' as data_confirmed, COUNT(*) AS FOUND, '6' AS EXPECTED
FROM "LIBRARY_CARD_CATALOG"."PUBLIC"."AUTHOR_INGEST_JSON"
UNION
SELECT 'Data-NESTED_INGEST_JSON' as data_confirmed, COUNT(*) AS FOUND, '5' AS EXPECTED
FROM "LIBRARY_CARD_CATALOG"."PUBLIC"."NESTED_INGEST_JSON"
UNION
SELECT 'Data-TWEET_INGEST' as data_confirmed, COUNT(*) AS FOUND, '9' AS EXPECTED
FROM "SOCIAL_MEDIA_FLOODGATES"."PUBLIC"."TWEET_INGEST"
UNION
SELECT 'Data-HASHTAGS_NORMALIZED' as data_confirmed, COUNT(*) AS FOUND, '14' AS EXPECTED
FROM "SOCIAL_MEDIA_FLOODGATES"."PUBLIC"."HASHTAGS_NORMALIZED"